Repository eclipse-jdt/eclipse.jdt.ui, pull requests merged in 2023-06, with the labels that each got.

#602 Automated Name Recommendation For The Extract Local Variable Refactoring
  org.eclipse.jdt.core.manipulation/META-INF/MANIFEST.MF
  org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/core/manipulation/StubUtility.java
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/ConvertForLoopOperation.java
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/ConvertIterableLoopOperation.java
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/ConvertLoopOperation.java
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/helper/WhileToForEach.java
  org.eclipse.jdt.core.manipulation/pom.xml
  org.eclipse.jdt.ui.tests.refactoring/META-INF/MANIFEST.MF
  org.eclipse.jdt.ui.tests.refactoring/pom.xml
  org.eclipse.jdt.ui.tests.refactoring/resources/ExtractTemp/canExtract/A_test153_in.java
  org.eclipse.jdt.ui.tests.refactoring/resources/ExtractTemp/canExtract/A_test153_out.java
  org.eclipse.jdt.ui.tests.refactoring/resources/ExtractTemp/canExtract/A_test154_in.java
  org.eclipse.jdt.ui.tests.refactoring/resources/ExtractTemp/canExtract/A_test154_out.java
  org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/ExtractTempTests.java
  org.eclipse.jdt.ui.tests/META-INF/MANIFEST.MF
  org.eclipse.jdt.ui.tests/pom.xml
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/ConvertLoopOperationTest.java
  org.eclipse.jdt.ui/META-INF/MANIFEST.MF
  org.eclipse.jdt.ui/pom.xml
Labels: enhancement

#599 Add null check to CreateObjectReferenceProposal.findReference()
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/proposals/CreateObjectReferenceProposal.java
Labels: bug

#624 Fix extract local to recognize super() and this() constructor calls
  org.eclipse.jdt.ui.tests.refactoring/resources/ExtractTemp/canExtract/A_test153_in.java
  org.eclipse.jdt.ui.tests.refactoring/resources/ExtractTemp/canExtract/A_test153_out.java
  org.eclipse.jdt.ui.tests.refactoring/resources/ExtractTemp/canExtract/A_test154_in.java
  org.eclipse.jdt.ui.tests.refactoring/resources/ExtractTemp/canExtract/A_test154_out.java
  org.eclipse.jdt.ui.tests.refactoring/resources/ExtractTemp/canExtract/A_test155_in.java
  org.eclipse.jdt.ui.tests.refactoring/resources/ExtractTemp/canExtract/A_test155_out.java
  org.eclipse.jdt.ui.tests.refactoring/resources/ExtractTemp/canExtract/A_test156_in.java
  org.eclipse.jdt.ui.tests.refactoring/resources/ExtractTemp/canExtract/A_test156_out.java
  org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/ExtractTempTests.java
  org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/code/ExtractTempRefactoring.java
Labels: bug

#600 Remove unused messages in JDT UI
  org.eclipse.jdt.ui/ui refactoring/org/eclipse/jdt/internal/ui/refactoring/RefactoringMessages.java
  org.eclipse.jdt.ui/ui refactoring/org/eclipse/jdt/internal/ui/refactoring/refactoringui.properties
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/JavaUIMessages.java
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/JavaUIMessages.properties
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/actions/ActionMessages.java
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/actions/ActionMessages.properties
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/jarpackagerfat/FatJarPackagerMessages.java
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/jarpackagerfat/FatJarPackagerMessages.properties
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/cleanup/CleanUpMessages.java
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/cleanup/CleanUpMessages.properties
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/formatter/FormatterMessages.java
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/formatter/FormatterMessages.properties
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/wizards/NewWizardMessages.java
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/wizards/NewWizardMessages.properties
Labels: enhancement

#586 Refactor NoStringCreationCleanUp to jdt.core.manipulation for jdt.ls use
  org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/fix/NoStringCreationCleanUpCore.java
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/fix/NoStringCreationCleanUp.java
Labels: enhancement

#609 Fix Bug 241035
  org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test56/in/A.java
  org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test56/in/B.java
  org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test56/in/C.java
  org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test56/out/A.java
  org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test56/out/B.java
  org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test56/out/C.java
  org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test57/in/A.java
  org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test57/in/B.java
  org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test57/in/C.java
  org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test57/out/A.java
  org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test57/out/B.java
  org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test57/out/C.java
  org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test58/in/A.java
  org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test58/in/B.java
  org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test58/in/C.java
  org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test58/out/A.java
  org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test58/out/B.java
  org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test58/out/C.java
  org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test59/in/A.java
  org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test59/in/B.java
  org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test59/in/C.java
  org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test59/out/A.java
  org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test59/out/B.java
  org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test59/out/C.java
  org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test60/in/A.java
  org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test60/in/B.java
  org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test60/in/C.java
  org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test60/out/A.java
  org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test60/out/B.java
  org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test60/out/C.java
  org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/PullUpTests.java
  org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/structure/HierarchyProcessor.java
  org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/structure/PullUpRefactoringProcessor.java
  org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/structure/PushDownRefactoringProcessor.java
Labels: bug

#587 Add support for extracting local from enhanced for statement
  org.eclipse.jdt.ui.tests.refactoring/resources/ExtractTemp/canExtract18/A_test120_in.java
  org.eclipse.jdt.ui.tests.refactoring/resources/ExtractTemp/canExtract18/A_test120_out.java
  org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/ExtractTempTests1d8.java
  org.eclipse.jdt.ui/core refactoring/org/eclipse/jdt/internal/corext/refactoring/code/ExtractTempRefactoring.java
Labels: bug

#585 Fix MissingCodeTabPage to work with select all/deselect all
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/cleanup/MissingCodeTabPage.java
Labels: bug

#580 Refactor VarCleanUp to jdt.core.manipulation for jdt.ls usage
  org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/fix/VarCleanUpCore.java
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/fix/VarCleanUp.java
Labels: enhancement

#588 Fix NewClassWizard to prevent final super classes
  org.eclipse.jdt.ui/META-INF/MANIFEST.MF
  org.eclipse.jdt.ui/pom.xml
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/proposals/NewCUUsingWizardProposal.java
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/wizards/NewClassWizardPage.java
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/wizards/NewTypeWizardPage.java
Labels: bug

#581 Fix for Bug 475462
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/VariableDeclarationFixCore.java
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest.java
Labels: bug

#625 Codeminingfilter
  org.eclipse.jdt.text.tests/META-INF/MANIFEST.MF
  org.eclipse.jdt.text.tests/pom.xml
  org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/codemining/ParameterNamesCodeMiningTest.java
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/codemining/CalleeJavaMethodParameterVisitor.java
Labels: enhancement

#634 Remove extraneous if case in EnumConstructorTargetFinder
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/EnumConstructorTargetFinder.java
Labels: bug

#640 Add new hover for Java hex, octal, and binary constants
  org.eclipse.jdt.ui/plugin.properties
  org.eclipse.jdt.ui/plugin.xml
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/hover/JavaConstantHover.java
Labels: enhancement, noteworthy

#635 Merge method ref simplification support into LambdaCleanUpFixCore
  org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/fix/LambdaExpressionsCleanUpCore.java
  org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/fix/MultiFixMessages.java
  org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/fix/MultiFixMessages.properties
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/CleanUpConstants.java
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/LambdaExpressionsFixCore.java
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AssistQuickFixTest1d8.java
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest1d8.java
  org.eclipse.jdt.ui/core extension/org/eclipse/jdt/internal/corext/fix/CleanUpConstantsOptions.java
  org.eclipse.jdt.ui/plugin.xml
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/cleanup/CleanUpMessages.java
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/cleanup/CleanUpMessages.properties
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/cleanup/JavaFeatureTabPage.java
Labels: enhancement, noteworthy

#646 Lambdainstanceof
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/LambdaExpressionAndMethodRefFixCore.java
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/LambdaExpressionsFixCore.java
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AssistQuickFixTest1d8.java
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest1d8.java
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/QuickAssistProcessor.java
Labels: enhancement
