Repository eclipse-jdt/eclipse.jdt.ui, pull requests merged in 2023-09, with the labels that each got.

#766 Don't offer to add type parameters to var type variable
  org.eclipse.jdt.core.manipulation/META-INF/MANIFEST.MF
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/Java50FixCore.java
  org.eclipse.jdt.core.manipulation/pom.xml
  org.eclipse.jdt.ui.tests/META-INF/MANIFEST.MF
  org.eclipse.jdt.ui.tests/pom.xml
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/LocalCorrectionsQuickFixTest10.java
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/QuickFixTestSuite.java
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/LocalCorrectionsSubProcessor.java
Labels: bug

#752 Preserve comment on variable cast when doing pattern instanceof cleanup
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/PatternMatchingForInstanceofFixCore.java
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest16.java
Labels: enhancement

#744 Add unicode support to Javadoc hover
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/hover/JavadocHoverTests.java
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/javadoc/JavadocContentAccess2.java
Labels: bug

#771 Ignore spelling in java string literals should apply to text blocks too
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/spelling/JavaSpellingEngine.java
Labels: bug

#711 Add logError(String) to Manipulations plugin
  org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/core/manipulation/JavaManipulationPlugin.java
Labels: enhancement

#718 Propose import quick fix for missing annotation value
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/QuickFixTest1d8.java
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/QuickFixProcessor.java
Labels: bug

#778 Don't make a field final if used in lambda exp used to initialize field
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/VariableDeclarationFixCore.java
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest1d8.java
Labels: bug

#787 Fix NPE for StringConcatToTextBlockFixCore
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/StringConcatToTextBlockFixCore.java
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest15.java
Labels: bug

#742 Improve hover for Java hex, octal, and binary constants
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/hover/JavaConstantHover.java
Labels: bug

#800 Tweak SuperTypeConstraintsCreator logic
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/structure/constraints/SuperTypeConstraintsCreator.java
Labels: enhancement

#799 performance: use JavaElementComparator in CleanUpRefactoringWizard
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/fix/CleanUpRefactoringWizard.java
Labels: performance

#802 Do further improvements to Java constant hover
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/hover/JavaConstantHover.java
Labels: bug

#827 Add back some missing methods to FixCorrectionProposal
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/proposals/FixCorrectionProposal.java
Labels: regression

#829 Fix FixCorrectionProposal to properly handle IMultiFix cleanups
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/proposals/FixCorrectionProposal.java
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/hover/AbstractAnnotationHover.java
Labels: regression

#830 Fix string concat to text block cleanup logic when in annotation
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/StringConcatToTextBlockFixCore.java
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/core/rules/Java15ProjectTestSetup.java
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest15.java
Labels: bug

#833 Mark newly split packages with mandatory directives
  org.eclipse.jdt.core.manipulation/META-INF/MANIFEST.MF
Labels: bug
