Repository eclipse-jdt/eclipse.jdt.ui, pull requests merged in 2024-07, with the labels that each got.

#1493 Refactor StaticInnerClassCleanUp to jdt.core.manipulation
  org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/fix/StaticInnerClassCleanUpCore.java
  org.eclipse.jdt.ui/plugin.xml
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/cleanup/PerformanceTabPage.java
Labels: enhancement

#1495 Refactor RedundantSemicolonsCleanUp to jdt.core.manipulation
  org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/fix/RedundantSemicolonsCleanUpCore.java
  org.eclipse.jdt.ui/plugin.xml
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/cleanup/UnnecessaryCodeTabPage.java
Labels: enhancement

#1497 Fix Javadoc hover for snippets to show type parameters
  org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/core/manipulation/internal/javadoc/CoreJavaDocSnippetStringEvaluator.java
Labels: bug

#1503 Do not flag spelling errors in Javadoc code or link tags
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/spelling/IJavaDocTagConstants.java
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/spelling/SpellCheckIterator.java
Labels: bug

#1506 Suggest import for missing type in a parenthesized cast expression
  org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/UnresolvedElementsBaseSubProcessor.java
Labels: bug

#1514 String support for if/else to switch cleanup
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/SwitchFixCore.java
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest12.java
Labels: enhancement, noteworthy

#1518 Enum support for if else to switch cleanup
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/SwitchFixCore.java
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest12.java
Labels: enhancement, noteworthy

#1519 Fix inline method to handle inner class static references
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/SourceProvider.java
  org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_in/Test_issue_1515_1.java
  org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_in/Test_issue_1515_2.java
  org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_in/Test_issue_1515_3.java
  org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_out/Test_issue_1515_1.java
  org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_out/Test_issue_1515_2.java
  org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_out/Test_issue_1515_3.java
  org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/InlineMethodTests.java
Labels: bug

#1522 Fix rename local to avoid field collision
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/RefactoringCoreMessages.java
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/refactoring.properties
  org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/rename/RenameLocalVariableProcessor.java
  org.eclipse.jdt.ui.tests.refactoring/resources/RenameTemp/canRename/A_test25_out.java
  org.eclipse.jdt.ui.tests.refactoring/resources/RenameTemp/canRename/A_test26_out.java
  org.eclipse.jdt.ui.tests.refactoring/resources/RenameTemp/canRename/A_test34_out.java
  org.eclipse.jdt.ui.tests.refactoring/resources/RenameTemp/canRename/A_test4_out.java
  org.eclipse.jdt.ui.tests.refactoring/resources/RenameTemp/cannotRename/A_test25.java
  org.eclipse.jdt.ui.tests.refactoring/resources/RenameTemp/cannotRename/A_test26.java
  org.eclipse.jdt.ui.tests.refactoring/resources/RenameTemp/cannotRename/A_test34.java
  org.eclipse.jdt.ui.tests.refactoring/resources/RenameTemp/cannotRename/A_test4.java
  org.eclipse.jdt.ui.tests.refactoring/resources/RenameTemp/cannotRename/A_testIssue_1508.java
  org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/RenameTempTests.java
Labels: bug

#1528 Tweak RenameLocalVariableProcessor.checkFieldCollision() logic
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/refactoring.properties
  org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/rename/RenameLocalVariableProcessor.java
  org.eclipse.jdt.ui.tests.refactoring/resources/RenameTemp/canRename/A_test4_in.java
  org.eclipse.jdt.ui.tests.refactoring/resources/RenameTemp/canRename/A_test4_out.java
  org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/RenameTempTests.java
Labels: bug

#1534 Fix lambda to method ref quick assist to not add type parameter
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/ConvertLambdaToMethodReferenceFixCore.java
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AssistQuickFixTest1d8.java
Labels: bug

#1537 Add additional logic to MoveInstanceMethodProcessor
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/RefactoringCoreMessages.java
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/refactoring.properties
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/structure/MoveInstanceMethodProcessor.java
  org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/cannotMove/testFail18/in/A.java
  org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/MoveInstanceMethodTests.java
Labels: bug

#1541 Fix local var cleanup to avoid method references
  org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/fix/VarCleanUpCore.java
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest11.java
Labels: bug

#1547 Fix MoveMembersTest failures due to moving to Java 1.8 as min version
  org.eclipse.jdt.ui.tests.refactoring/resources/MoveMembers/testFail19/in/A.java
  org.eclipse.jdt.ui.tests.refactoring/resources/MoveMembers/testFail19/in/B.java
  org.eclipse.jdt.ui.tests.refactoring/resources/MoveMembers/testFail21/in/A.java
  org.eclipse.jdt.ui.tests.refactoring/resources/MoveMembers/testFail21/in/B.java
  org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/MoveMembersTests.java
Labels: bug

#1561 Fix StringBuffer to text block to allow passing as string argument
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/StringConcatToTextBlockFixCore.java
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AssistQuickFixTest15.java
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest15.java
Labels: enhancement
