Repository eclipse-jdt/eclipse.jdt.ui, pull requests merged in 2024-10, with the labels that each got.

#1690 Fix push down to recognize super class name collisions
  org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/structure/PushDownRefactoringProcessor.java
  org.eclipse.jdt.ui.tests.refactoring/resources/PushDown/test39/in/A.java
  org.eclipse.jdt.ui.tests.refactoring/resources/PushDown/test39/out/A.java
  org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/PushDownTests.java
Labels: bug

#1693 Fix push down to allow moving fields/methods to inner/local classes
  org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/structure/PushDownRefactoringProcessor.java
  org.eclipse.jdt.ui.tests.refactoring/resources/PushDown/test40/in/A.java
  org.eclipse.jdt.ui.tests.refactoring/resources/PushDown/test40/out/A.java
  org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/PushDownTests.java
Labels: bug

#1694 Fix push down to replace super references where appropriate
  org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/structure/PushDownRefactoringProcessor.java
  org.eclipse.jdt.ui.tests.refactoring/resources/PushDown/test41/in/A.java
  org.eclipse.jdt.ui.tests.refactoring/resources/PushDown/test41/out/A.java
  org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/PushDownTests.java
Labels: bug

#1671 Move filters Button in Call Hierarchy view to the top level Bar
  org.eclipse.jdt.ui/META-INF/MANIFEST.MF
  org.eclipse.jdt.ui/pom.xml
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/callhierarchy/CallHierarchyFiltersActionGroup.java
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/callhierarchy/CallHierarchyViewPart.java
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/callhierarchy/ShowCallHierarchyFilterDialogAction.java
Labels: enhancement

#1709 Text block conversion support for indexOf()
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/StringConcatToTextBlockFixCore.java
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AssistQuickFixTest15.java
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest15.java
Labels: enhancement

#1717 Modify string concat to text block cleanup to handle empty strings
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/StringConcatToTextBlockFixCore.java
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest15.java
Labels: bug

#1718 Fix illegal name exception when inlining qualified field name
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/InlineTempRefactoring.java
  org.eclipse.jdt.ui.tests.refactoring/resources/InlineTemp/canInline/A_test65_in.java
  org.eclipse.jdt.ui.tests.refactoring/resources/InlineTemp/canInline/A_test65_out.java
  org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/InlineTempTests.java
Labels: bug

#1724 Fix set up for VisitorTest now that ASTParser has changed
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/internal/common/VisitorTest.java
Labels: bug

#1720 Fix unused suppressed warnings quick fix counts
  org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/fix/UnusedSuppressWarningsCleanUp.java
  org.eclipse.jdt.core.manipulation/proposals/org/eclipse/jdt/internal/ui/text/correction/SuppressWarningsBaseSubProcessor.java
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/QuickFixTest1d8.java
Labels: bug

#1726 Fix if/else to switch to handle null scenarios
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/SwitchFixCore.java
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest12.java
Labels: bug

#1732 Fix smart paste to not import when pasting into string or text block
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/ClipboardOperationAction.java
Labels: bug

#1747 Add new quick fix for unused pattern variable / unused lambda variable
  org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/fix/RenameUnusedVariableCleanUpCore.java
  org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/fix/UnusedCodeCleanUpCore.java
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/FixMessages.java
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/FixMessages.properties
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/RenameUnusedVariableFixCore.java
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/UnusedCodeFixCore.java
  org.eclipse.jdt.ui.tests/test plugin/org/eclipse/jdt/testplugin/JavaProjectHelper.java
  org.eclipse.jdt.ui.tests/test plugin/org/eclipse/jdt/testplugin/util/CreateStubsAction.java
  org.eclipse.jdt.ui.tests/testresources/rtstubs-README.txt
  org.eclipse.jdt.ui.tests/testresources/rtstubs_22.jar
  org.eclipse.jdt.ui.tests/testresources/rtstubs_23.jar
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/core/rules/Java22ProjectTestSetup.java
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/QuickFixTest22.java
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/QuickFixTestSuite.java
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/LocalCorrectionsSubProcessor.java
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/QuickFixProcessor.java
Labels: enhancement, noteworthy

#1759 Fix array indexing exception in PushDownRefactoringProcessor
  org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/structure/PushDownRefactoringProcessor.java
Labels: bug
