Repository eclipse-jdt/eclipse.jdt.ui, pull requests merged in 2024-06, with the labels that each got.

#1412 Fix move instance method when inner class is referenced
  org.eclipse.jdt.core.manipulation/META-INF/MANIFEST.MF
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/structure/MoveInstanceMethodProcessor.java
  org.eclipse.jdt.ui.tests.refactoring/META-INF/MANIFEST.MF
  org.eclipse.jdt.ui.tests.refactoring/pom.xml
  org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test71/in/A.java
  org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test71/out/A.java
  org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test72/in/A.java
  org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test72/out/A.java
  org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test73/in/A.java
  org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test73/in/B.java
  org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test73/out/A.java
  org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test73/out/B.java
  org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test74/in/A.java
  org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test74/in/B.java
  org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test74/out/A.java
  org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test74/out/B.java
  org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test75/in/A.java
  org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test75/out/A.java
  org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test76/in/A.java
  org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test76/in/B.java
  org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test76/out/A.java
  org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test76/out/B.java
  org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/MoveInstanceMethodTests.java
Labels: bug

#1413 Fix move instance processor to handle class instance creation accessibility
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/structure/MoveInstanceMethodProcessor.java
  org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test77/in/A.java
  org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test77/out/A.java
  org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test78/in/A.java
  org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test78/in/B.java
  org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test78/out/A.java
  org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test78/out/B.java
  org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/MoveInstanceMethodTests.java
Labels: bug

#1430 Fix NPE in QuickFixProcessor
  org.eclipse.jdt.ui/META-INF/MANIFEST.MF
  org.eclipse.jdt.ui/pom.xml
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/QuickFixProcessor.java
Labels: bug

#1415 Fix false error on extraction of for loop contents
  org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/code/ExtractMethodAnalyzer.java
  org.eclipse.jdt.ui.tests.refactoring/resources/ExtractMethodWorkSpace/ExtractMethodTests/branch_in/A_test770.java
  org.eclipse.jdt.ui.tests.refactoring/resources/ExtractMethodWorkSpace/ExtractMethodTests/branch_out/A_test770.java
  org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/ExtractMethodTests.java
Labels: bug

#1418 Fix false extract method failure due to local variable access
  org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/code/ExtractMethodAnalyzer.java
  org.eclipse.jdt.ui.tests.refactoring/resources/ExtractMethodWorkSpace/ExtractMethodTests/locals_in/A_test579.java
  org.eclipse.jdt.ui.tests.refactoring/resources/ExtractMethodWorkSpace/ExtractMethodTests/locals_out/A_test579.java
  org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/ExtractMethodTests.java
Labels: bug

#1423 Fix concat to MessageFormat and String.format
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/ConvertToMessageFormatFixCore.java
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/ConvertToStringFormatFixCore.java
  org.eclipse.jdt.ui.tests/META-INF/MANIFEST.MF
  org.eclipse.jdt.ui.tests/pom.xml
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AssistQuickFixTest15.java
Labels: bug

#1427 Fix move method to handle field access modifier adjustment
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/structure/MoveInstanceMethodProcessor.java
  org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test79/in/A.java
  org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test79/out/A.java
  org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/MoveInstanceMethodTests.java
Labels: bug

#1441 Fix code mining parameter name logic
  org.eclipse.jdt.ui/META-INF/MANIFEST.MF
  org.eclipse.jdt.ui/pom.xml
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/codemining/CalleeJavaMethodParameterVisitor.java
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/JavaEditorCodeMiningConfigurationBlock.java
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/PreferencesMessages.java
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/PreferencesMessages.properties
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/PreferenceConstants.java
Labels: bug

#1435 Fix Bug 202162 - JUnit messages says failed first but it is not
  org.eclipse.jdt.junit/META-INF/MANIFEST.MF
  org.eclipse.jdt.junit/src/org/eclipse/jdt/internal/junit/ui/JUnitMessages.java
  org.eclipse.jdt.junit/src/org/eclipse/jdt/internal/junit/ui/JUnitMessages.properties
  org.eclipse.jdt.junit/src/org/eclipse/jdt/internal/junit/ui/TestRunnerViewPart.java
Labels: bug

#1447 Fix inlining method returning constant into switch expression
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/CallInliner.java
  org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/simple14_in/TestSwitchExpression8.java
  org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/simple14_out/TestSwitchExpression8.java
  org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/InlineMethodTests16.java
Labels: bug

#1457 Fix NPE in OverriddenAssignmentFixCore moveDown method
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/OverriddenAssignmentFixCore.java
Labels: bug

#1453 Fix move of record to new file refactoring when component accessed
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/structure/MemberVisibilityAdjustor.java
  org.eclipse.jdt.ui.tests.refactoring/resources/MoveInnerToNew14/moveInnerRecord2/in/p1/Foo.java
  org.eclipse.jdt.ui.tests.refactoring/resources/MoveInnerToNew14/moveInnerRecord2/out/p1/Bar.java
  org.eclipse.jdt.ui.tests.refactoring/resources/MoveInnerToNew14/moveInnerRecord2/out/p1/Foo.java
  org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/MoveInnerToNewTests16.java
Labels: bug

#1463 Fix adding null annotation to qualified type of parameter
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/NullAnnotationsQuickFixTest.java
  org.eclipse.jdt.ui/core extension/org/eclipse/jdt/internal/corext/fix/NullAnnotationsRewriteOperations.java
Labels: bug, null

#1474 Fix inlined return message to not clip white-space
  org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/core/manipulation/internal/javadoc/CoreJavadocAccessImpl.java
Labels: bug

#1477 Allow optional default case label if switch missing all statements
  org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/CorrectionMessages.java
  org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/CorrectionMessages.properties
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AssistQuickFixTest.java
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/LocalCorrectionsQuickFixTest.java
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/QuickFixTest14.java
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/LocalCorrectionsSubProcessor.java
Labels: enhancement

#1479 Add support for extracting method to outer class
  org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/code/ExtractMethodAnalyzer.java
  org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/code/ExtractMethodRefactoring.java
  org.eclipse.jdt.ui.tests.refactoring/resources/ExtractMethodWorkSpace/ExtractMethodTests/nested_in/A_test655.java
  org.eclipse.jdt.ui.tests.refactoring/resources/ExtractMethodWorkSpace/ExtractMethodTests/nested_out/A_test655.java
  org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/ExtractMethodTests.java
Labels: bug

#1446 Add quickfix to suggest types for constructor type mismatch
  org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/CorrectionMessages.java
  org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/CorrectionMessages.properties
  org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/text/correction/TypeMismatchBaseSubProcessor.java
  org.eclipse.jdt.core.manipulation/proposals/org/eclipse/jdt/internal/ui/text/correction/proposals/TypeChangeCorrectionProposalCore.java
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/TypeMismatchQuickFixTests.java
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/TypeMismatchSubProcessor.java
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/correction/proposals/TypeChangeCorrectionProposal.java
Labels: enhancement
