Repository eclipse-jdt/eclipse.jdt.ui, pull requests merged in 2024-08, with the labels that each got.

#1574 Update InlineTempRefactoring logic for adding method type parameters
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/InlineTempRefactoring.java
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/rename/RefactoringAnalyzeUtil.java
  org.eclipse.jdt.ui.tests.refactoring/resources/InlineTemp/canInline/A_test31_out.java
  org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/InlineTempTests.java
Labels: bug

#1576 Fix extract method to recognize name collision with a sub-class
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/RefactoringCoreMessages.java
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/refactoring.properties
  org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/code/ExtractMethodRefactoring.java
  org.eclipse.jdt.ui.tests.refactoring/resources/ExtractMethodWorkSpace/ExtractMethodTests/invalidSelection/A_testIssue1516.java
  org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/ExtractMethodTests.java
Labels: bug

#1584 Clarify message when refactoring rename not possible
  org.eclipse.jdt.ui/ui refactoring/org/eclipse/jdt/internal/ui/refactoring/refactoringui.properties
Labels: enhancement

#1590 Add outer class checking to Pull Up Refactoring
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/RefactoringCoreMessages.java
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/refactoring.properties
  org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/structure/PullUpRefactoringProcessor.java
  org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test61/in/A.java
  org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test61/out/A.java
  org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test62/in/A.java
  org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test62/out/A.java
  org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/testFail30/in/A.java
  org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/testFail31/in/A.java
  org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/testFail32/in/A.java
  org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/testFail33/in/A.java
  org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/testFail34/in/A.java
  org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/PullUpTests.java
Labels: bug

#1616 [23] Tests for link completion inside markdown comments.
  org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/contentassist/CodeCompletionTest23.java
  org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/contentassist/ContentAssistTestSuite.java
  org.eclipse.jdt.ui.tests/test plugin/org/eclipse/jdt/testplugin/JavaProjectHelper.java
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/core/rules/Java23ProjectTestSetup.java
Labels: test
