Repository eclipse-jdt/eclipse.jdt.ui, pull requests merged in 2025-04, with the labels that each got.

#2124 Ensure unused suppress warnings cleanup uses it own compiler options
  org.eclipse.jdt.core.manipulation/META-INF/MANIFEST.MF
  org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/fix/UnusedSuppressWarningsCleanUp.java
  org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/ui/cleanup/CleanUpRequirements.java
  org.eclipse.jdt.ui/core extension/org/eclipse/jdt/internal/corext/fix/CleanUpRefactoring.java
Labels: bug

#2126 Allow inlining in lambda to support multiple statement methods
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/CallInliner.java
  org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_in/Test_issue_2111_2.java
  org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_in/Test_issue_2118_3.java
  org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_out/Test_issue_2111_2.java
  org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_out/Test_issue_2118_3.java
  org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/InlineMethodTests.java
Labels: enhancement

#2148 Add support for trailing return or throws for pattern instanceof cleanup
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/PatternInstanceofToSwitchFixCore.java
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest21.java
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest22.java
Labels: bug

#2084 Added Switch Statment and Switch Expression to the new folding
  org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/folding/FoldingTest.java
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/text/folding/DefaultJavaFoldingStructureProvider.java
Labels: enhancement, noteworthy

#2151 Reset source to result group source when using search in push down
  org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/structure/PushDownRefactoringProcessor.java
Labels: bug

#2153 Fix convert to lambda method reference to recognize a lambda parm
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/ConvertLambdaToMethodReferenceFixCore.java
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AssistQuickFixTest1d8.java
Labels: bug

#2167 Do not add always add final field qualifier when compilation unit has errors
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/VariableDeclarationFixCore.java
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/AssistQuickFixTest.java
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest.java
Labels: bug

#2181 Fix quick fix for missing type in enhanced for loop
  org.eclipse.jdt.core.manipulation/proposals/org/eclipse/jdt/internal/ui/text/correction/proposals/NewVariableCorrectionProposalCore.java
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/UnresolvedTypesQuickFixTest.java
Labels: bug

#2193 Fix pull up refactoring to properly replace this argument when needed
  org.eclipse.jdt.core.manipulation/refactoring/org/eclipse/jdt/internal/corext/refactoring/structure/PullUpRefactoringProcessor.java
  org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test56/out/A.java
  org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test57/out/A.java
  org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test58/out/A.java
  org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test59/out/A.java
  org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test63/in/A.java
  org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test63/in/B.java
  org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test63/out/A.java
  org.eclipse.jdt.ui.tests.refactoring/resources/PullUp/test63/out/B.java
  org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/PullUpTests.java
Labels: bug
