Repository eclipse-jdt/eclipse.jdt.ui, pull requests merged in 2025-03, with the labels that each got.

#2050 Fix completion of annotation in package-info.java to not fully qualify
  org.eclipse.jdt.text.tests/META-INF/MANIFEST.MF
  org.eclipse.jdt.text.tests/pom.xml
  org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/contentassist/CodeCompletionTest1d8.java
  org.eclipse.jdt.ui/META-INF/MANIFEST.MF
  org.eclipse.jdt.ui/pom.xml
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/LazyJavaTypeCompletionProposal.java
Labels: bug

#2044 Fix add import operation to avoid name collision
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/codemanipulation/CodeGenerationMessages.java
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/codemanipulation/CodeGenerationMessages.properties
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/core/AddImportTest.java
  org.eclipse.jdt.ui/core extension/org/eclipse/jdt/internal/corext/codemanipulation/AddImportsOperation.java
Labels: bug

#2031 Add checking for import collision when moving methods
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/structure/MoveInstanceMethodProcessor.java
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/structure/MoveStaticMembersProcessor.java
  org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test81/in/A.java
  org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test81/in/B.java
  org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test81/in/a/T.java
  org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test81/in/b/T.java
  org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test81/out/A.java
  org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test81/out/B.java
  org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test81/out/a/T.java
  org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test81/out/b/T.java
  org.eclipse.jdt.ui.tests.refactoring/resources/MoveMembers/test64/in/A.java
  org.eclipse.jdt.ui.tests.refactoring/resources/MoveMembers/test64/in/B.java
  org.eclipse.jdt.ui.tests.refactoring/resources/MoveMembers/test64/in/a/T.java
  org.eclipse.jdt.ui.tests.refactoring/resources/MoveMembers/test64/in/b/T.java
  org.eclipse.jdt.ui.tests.refactoring/resources/MoveMembers/test64/out/A.java
  org.eclipse.jdt.ui.tests.refactoring/resources/MoveMembers/test64/out/B.java
  org.eclipse.jdt.ui.tests.refactoring/resources/MoveMembers/test64/out/a/T.java
  org.eclipse.jdt.ui.tests.refactoring/resources/MoveMembers/test64/out/b/T.java
  org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/MoveInstanceMethodTests.java
  org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/MoveMembersTests.java
Labels: bug

#2035 Add method reference support to Call hierarchy callee tree
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/callhierarchy/CalleeAnalyzerVisitor.java
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/callhierarchy/CallHierarchyContentProviderTest.java
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/callhierarchy/CallHierarchyTestHelper.java
Labels: bug

#2018 Add pattern name fixing for pattern instanceof to switch for Java 22
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/PatternInstanceofToSwitchFixCore.java
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest22.java
Labels: enhancement, noteworthy

#2058 Fix adding blocks to not duplicate comment in else
  org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/fix/ControlStatementsCleanUp.java
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/ControlStatementsFix.java
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpStressTest.java
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest.java
Labels: bug

#1825 custom folding regions
  org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/JdtTextTestSuite.java
  org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/folding/CustomFoldingRegionTest.java
  org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/folding/FoldingTestSuite.java
  org.eclipse.jdt.ui/META-INF/MANIFEST.MF
  org.eclipse.jdt.ui/pom.xml
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/folding/DefaultJavaFoldingPreferenceBlock.java
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/folding/FoldingMessages.java
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/folding/FoldingMessages.properties
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/PreferenceConstants.java
  org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/text/folding/DefaultJavaFoldingStructureProvider.java
Labels: enhancement, noteworthy

#2064 Fix add blocks when then statement is on same line as if and nls comment
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/ControlStatementsFix.java
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest.java
Labels: bug

#2065 Fix add block to handle if expressions over multiple lines
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/ControlStatementsFix.java
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest.java
Labels: bug

#2034 Add Filter Mechanism for Target in Move Refactoring - with caching
  org.eclipse.jdt.ui/ui refactoring/org/eclipse/jdt/internal/ui/refactoring/reorg/DestinationContentProvider.java
  org.eclipse.jdt.ui/ui refactoring/org/eclipse/jdt/internal/ui/refactoring/reorg/ReorgUserInputPage.java
Labels: enhancement, noteworthy

#2072 Fix some pattern instanceof to switch cleanup errors
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/PatternInstanceofToSwitchFixCore.java
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest21.java
Labels: bug

#2077 Enable null case recognition in PatternInstanceofToSwitchFixCore
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/PatternInstanceofToSwitchFixCore.java
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest21.java
Labels: bug, noteworthy

#2080 Fix NullAnnotationsRewriteOperations to handle AnnotatableType
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/QuickFixTest1d8.java
  org.eclipse.jdt.ui/core extension/org/eclipse/jdt/internal/corext/fix/NullAnnotationsRewriteOperations.java
Labels: bug

#2088 Fix indenting of various UI tests after fixing core indenting
  org.eclipse.jdt.ui.tests.refactoring/resources/ConvertAnonymousToNested/canConvert/A_test33_out.java
  org.eclipse.jdt.ui.tests.refactoring/resources/MoveInstanceMethod/canMove/test54/out/A.java
  org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/PullUpTests.java
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/core/source/GenerateHashCodeEqualsTest.java
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/ModifierCorrectionsQuickFixTest.java
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/UnresolvedMethodsQuickFixTest.java
Labels: enhancement

#2102 Add conditional expression support to pattern instanceof cleanup
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/PatternMatchingForInstanceofFixCore.java
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest16.java
Labels: enhancement

#2104 Fix Pattern instanceof cleanup to handle casts in the if statement
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/fix/PatternMatchingForInstanceofFixCore.java
  org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/CleanUpTest16.java
Labels: enhancement, noteworthy

#2121 Allow an empty method to be inlined in a lambda expression body
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/CallInliner.java
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/SourceProvider.java
  org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_in/Test_issue_2111_1.java
  org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_out/Test_issue_2111_1.java
  org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/InlineMethodTests.java
Labels: bug

#2122 Fix inlining to support method references
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/CallInliner.java
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/Invocations.java
  org.eclipse.jdt.core.manipulation/core extension/org/eclipse/jdt/internal/corext/refactoring/code/TargetProvider.java
  org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_in/Test_issue_2118_1.java
  org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_in/Test_issue_2118_2.java
  org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_out/Test_issue_2118_1.java
  org.eclipse.jdt.ui.tests.refactoring/resources/InlineMethodWorkspace/TestCases/bugs_out/Test_issue_2118_2.java
  org.eclipse.jdt.ui.tests.refactoring/test cases/org/eclipse/jdt/ui/tests/refactoring/InlineMethodTests.java
Labels: bug
